### PR TITLE
fix postponed annotation when field is overwritten

### PR DESCRIPTION
**Pull request by mixilchenko**
Thanks to @zhiruiluo #183 covers the main problem described in #168.
However, I want to cover one more case when subclass definition overwrites variable type with specific subtype.

### CODE REVIEW

**Comment by lebrice** [comment]
Hey @mixilchenko , thanks for making this.

I'm having a bit of trouble understanding what case this is fixing. Would you mind adding some docstrings in the test explaining a bit more what the test is checking? It's not thaaat easy to understand the test from just looking at the current code.

**Review by lebrice — CHANGES_REQUESTED** [review]
Hey @mixilchenko , thanks for making this.

I'm having a bit of trouble understanding what case this is fixing. Would you mind adding some docstrings in the test explaining a bit more what the test is checking? It's not thaaat easy to understand the test from just looking at the current code.

**Comment by mixilchenko** [comment]
I tried to improve naming and added some docstrings to highlight the difference between these two tests

**Review by lebrice — APPROVED** [review]
Thanks @mixilchenko !

**Pull request merged**
